# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: StarPilot Docs
site_url: https://starpilot.sherloaf.com
site_description: Documentation for the install and usage of StarPilot

nav:
  - Introduction: index.md
  - Required Hardware: 
    - Bolt EV: hardware/bolt.md
    - Volt & Other ASCM/SDGM Cars: hardware/volt.md
  - Hardware Installation:
    - Comma 3X: install/comma.md
    - Pedal: install/pedal.md
    - Car Config: install/car.md
  - Software Installation:
    - Install StarPilot: software/starpilot.md
    - Configure Toggles: software/toggles.md
  - Pedal Firmware Flash: pedal-firmware.md

theme:
    name: material
    custom_dir: overrides
    palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: green
      secondary: green
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: green
      secondary: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      secondary: green
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

    logo: assets/images/starpilot_icon--small.png
    
    icon:
        repo: fontawesome/brands/github
        
    features:
        - navigation.instant
        - navigation.sections
        - navigation.footer
        - toc.follow
        

markdown_extensions:
          - admonition
          - tables
          - toc:
              permalink: true
          - pymdownx.details
          - pymdownx.superfences
          - pymdownx.critic
          - pymdownx.caret
          - pymdownx.keys
          - pymdownx.mark
          - pymdownx.tilde
          - attr_list
          
plugins:
    - search
    - social
    - git-revision-date-localized:
        enable_creation_date: true
        type: date
    - git-committers:
        repository: StarPilot-Docs/docs
        branch: main
    - callouts

repo_url: https://github.com/firestar5683/StarPilot
repo_name: firestar5683/StarPilot

extra:
    social:
      - icon: fontawesome/brands/discord
        link: https://discord.com/channels/1137853399715549214/1415794762312581222
